import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:biometric/config/constants.dart';
import 'package:biometric/providers/auth_provider.dart';
import 'package:biometric/providers/location_provider.dart';
import 'package:biometric/providers/attendance_provider.dart';
import 'package:biometric/screens/auth/login_screen.dart';
import 'package:biometric/screens/employee/employee_dashboard.dart';
import 'package:biometric/screens/admin/admin_dashboard.dart';

void main() async {
  // Ensure Flutter engine bindings are initialized prior to loading native dependencies
  WidgetsFlutterBinding.ensureInitialized();
  
  // Note: Firebase.initializeApp() requires a configuration file generated by Flutterfire CLI (options).
  // The user will configure this on their local workspace using `flutterfire configure`.
  // We initialize gracefully, catching missing default setup errors for standard offline builds.
  try {
    await Firebase.initializeApp();
  } catch (e) {
    print('Firebase initialization notice: ${e.toString()}');
  }

  runApp(const BiometricAttendanceApp());
}

class BiometricAttendanceApp extends StatelessWidget {
  const BiometricAttendanceApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => LocationProvider()),
        ChangeNotifierProvider(create: (_) => AttendanceProvider()),
      ],
      child: MaterialApp(
        title: AppConstants.appName,
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          useMaterial3: true,
          brightness: Brightness.dark,
          scaffoldBackgroundColor: AppConstants.background,
          primaryColor: AppConstants.primary,
          colorScheme: const ColorScheme.dark(
            primary: AppConstants.primary,
            secondary: AppConstants.secondary,
            background: AppConstants.background,
            surface: AppConstants.cardBg,
            error: AppConstants.error,
          ),
          fontFamily: 'Roboto', // Premium modern fallback typeface
          appBarTheme: const AppBarTheme(
            backgroundColor: AppConstants.background,
            elevation: 0,
            iconTheme: IconThemeData(color: Colors.white),
          ),
        ),
        home: const AuthSessionGate(),
      ),
    );
  }
}

class AuthSessionGate extends StatelessWidget {
  const AuthSessionGate({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (context, auth, child) {
        // 1. Show beautiful loader during session verify states
        if (auth.isLoading) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(AppConstants.primary),
              ),
            ),
          );
        }

        // 2. Redirect to Login if no active user session is present
        if (auth.currentUser == null) {
          return const LoginScreen();
        }

        // 3. Session is authenticated! Determine role layout route
        if (auth.currentUser!.role == 'admin') {
          return const AdminDashboard();
        } else {
          return const EmployeeDashboard();
        }
      },
    );
  }
}
